# Project Information
site_name: Philippines vACC Knowledge Base
site_url: https://learn.vatphil.com
site_author: Jacob Allen, Juan Carlos. Inspired by Kenzo Tayko, Emilio Perez and Michael Uy
edit_uri: edit/main/docs/
copyright: Copyright © 2026 Philippines vACC. All rights reserved. This site is not affiliated with the CAAP, the actual Philippines ACC, or any governing aviation body. All content contained herein is approved only for use on the VATSIM network.

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      exclude:
        - index.md
  - mike
  - glightbox
  
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js

# Configuration
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  custom_dir: overrides
  font:
    text: Mulish
  palette:
    - scheme: vatphil
      primary: 
      accent: amber
  logo: assets/img/vatphil-wlogo.png
  favicon: assets/img/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.prune
    - search.suggest
    - search.highlight
    - search.share
    - content.footnote.tooltips
    - content.tooltips
    - content.tabs.link

extra_css:
  - stylesheets/vatphil.css
  - https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css

extra:
  analytics:
    provider: google
    property: G-779QHKRL0K
  social:
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/philippinesvacc
      name: Facebook Page
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vatphil
      name: Instagram
    - icon: material/home
      link: https://vatphil.com
      name: Philippines vACC Main Website
    - icon: simple/discord
      link: https://community.vatsim.net/
      name: Join our Discord!
    - icon: material/email
      link: mailto:staff@vatphil.com
      name: Contact Us

  version:
    provider: mike


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  - abbr
  - pymdownx.snippets
  - toc:
      permalink: true
